---
title: "Core Microbiome"
output: html_document
---

```{r functions, echo=FALSE}

library("phyloseq"); library("grid");

tidy_phyloseq <- function(my_phyloseq){
  # set ranks. 
  colnames(tax_table(my_phyloseq)) = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
  # fix taxa names
  tax_table(my_phyloseq)[,colnames(tax_table(my_phyloseq))] <- gsub(tax_table(my_phyloseq)[,colnames(tax_table(my_phyloseq))],pattern="[a-z]__",replacement="")
  # If NA in phylum position of taxonomy table then change it to "Unidentified"
  tax_table(my_phyloseq)[tax_table(my_phyloseq)[,"Phylum"]==NA,"Phylum"] <- "Unidentified"
  return(my_phyloseq)
}

# core microbiome function
# finds the core microbiome with various options
# physeq: the phyloseq object to query
# threshold: the abundance below which OTUs are not regarded as being "core taxa"
# method: "max" or "mean" - define whether to calculate the threshold for the max or mean
# ranks: vector of taxonomic ranks at which to search for the core taxa

# Note.
# max and mean are calculated for the whole OTU table per row
# therefore
# mean gives the overall abundant OTUs
# max will include any OTU which is abundant any 1 sample, so it is really like a sample-wise search

# Defaults are set to model the typical scenario where simple abundance across the whole
# experiment are used to identify numerically dominant OTUs
# returns a list of OTUs
core_microbiome <- function(physeq,threshold=2,method="mean",ranks=c("Species"),verbose=0){
  core_otus_glom <- c()
  for (rank in ranks) {
    # agglomerate to the taxonomic rank being searched
    # but only do this if we are not at the bottom rank already
    if(rank!=rank_names(physeq)[length(rank_names(physeq))]) {
      physeq.glom <- tax_glom(physeq,rank)
    } else {
      physeq.glom <- physeq
    }
    # get the OTU table into a dataframe
    glom_otus <- as.data.frame(otu_table(physeq.glom))
    # calculate the test statistic for each OTU
    glom_otus$stat <- apply(glom_otus,1,method)
    # make a list of the taxa meeting the abundance criteria
    glom_rank_candidates <- row.names(glom_otus[glom_otus$stat >= threshold,])
    # identify the taxonomy of the candidates
    glom_rank_taxonomy <- tax_table(physeq.glom)[glom_rank_candidates,rank]
    # identify the most abundant OTU within the identified taxonomic group, and add it to the list
    # tax_glom does not always pick the most abundant OTU in the classification
    # Therefore need to specifically check for the most abundant OTU 
    # should only do this if we are not working at the lowest rank in the phyloseq object
    if(rank!=rank_names(physeq)[length(rank_names(physeq))]) {
      for (candidate in glom_rank_taxonomy) {
        OTUs_in_taxonomic_group <- tax_table(physeq)[,rank] == as.character(candidate)
        most_abundant_OTU <- names(which.max(taxa_sums(physeq)[as.vector(OTUs_in_taxonomic_group)]))
        core_otus_glom <- c(core_otus_glom,most_abundant_OTU)
      }
    } 
    else {
      # at OTU level we don't need to search for the most abundant one - we want them all
      core_otus_glom <- c(core_otus_glom,glom_rank_candidates)  
    }
    
    if(verbose>1)  print(paste(rank,"level search found",length(glom_rank_candidates),"taxa above",method,"abundance of",threshold))
  }
  if(verbose>0) print(paste("Search found", length(core_otus_glom),"unique OTUs"))
  return(unique(core_otus_glom))
}

# core compare function
# Input 2 phyloseq objects which have been pruned to contain a 'core microbiome'
# returns nothing
# prints a list of extra OTUs in the first object, not present in the second
# Identifies extra taxonomic groups represented by those OTUs, which are not present in the second object
core_compare <- function(physeq1,physeq2) {
  # Find out which OTUs were added by the multi-rank approach
  extras <- tax_table(physeq1)[!rownames(otu_table(physeq1))%in%rownames(otu_table(physeq2))]
  cat(c("Extra OTUs: ", rownames(extras)))
  cat("\nExtra taxa represented in first object\n")
  # Find out which taxa are additionally represented by those OTUs
  for(rank in rank_names(physeq1)) {
    cat(rank)
    index <- !extras[,rank]%in%unique(tax_table(physeq2)[,rank])
    if(sum(index)) {
      cat(c("\n",unique(as.vector(extras[index,rank])),"\n"))
    }
    else {
      cat(c("\n","none","\n"))
    }
  }
}


```


```{r load_date,echo=FALSE}

# Kalahari bacteria
biom <- import_biom("data/kb/otu_table.biom",taxaPrefix="X")
map <- import_qiime_sample_data(mapfilename="data/kb/map.txt")
kb <- merge_phyloseq(biom, map)
kb <- tidy_phyloseq(kb)

### Holme Moss bacteria
biom <- import_biom("data/hb/otu_table.biom",taxaPrefix="X")
map <- import_qiime_sample_data(mapfilename="data/hb/map.txt")
tax_assignments <- read.delim("data/hb/tax.txt", header=F)
row.names(tax_assignments) <- tax_assignments$V1
taxonomy <- as.matrix(tax_assignments[2:8])
tax = tax_table(taxonomy)
hb <- merge_phyloseq(biom, map, tax)
hb <- tidy_phyloseq(hb)

### Holme Moss fungi
biom <- import_biom("data/hf/otu_table.biom",taxaPrefix="X")
map <- import_qiime_sample_data(mapfilename="data/hf/map.txt")
tax <- read.delim("data/hf/tax.txt")

tax_assignments <- read.delim("data/hf/tax.txt", header=F)
row.names(tax_assignments) <- tax_assignments$V1
taxonomy <- as.matrix(tax_assignments[2:8])
tax = tax_table(taxonomy)
hf <- merge_phyloseq(biom, map, tax)
hf <- tidy_phyloseq(hf)

# convert OTU observations into relative abundance per sample
kb.rel <- transform_sample_counts(kb, function(x) 100*x/(sum(x)))
hb.rel <- transform_sample_counts(hb, function(x) 100*x/(sum(x)))
hf.rel <- transform_sample_counts(hf, function(x) 100*x/(sum(x)))

```


```{r core_OTU, fig.width=18, fig.height=15}

expts <- c(kb.rel , hb.rel , hf.rel)
studies <- c("dryland bacteria" , "peatland bacteria" , "peatland fungi")

for ( i in 1:length(expts) ) {
  expt <- expts[[i]]
  study <- studies[i]
  print(study)
  otus <- as.data.frame(otu_table(expt))
  
  # Identify core OTUs using different options
  # then make a pruned phyloseq object for each list
  species_mean <- core_microbiome(expt,threshold=2,method="mean",ranks=c("Species"))
  expt.species_mean <- prune_taxa(species_mean,expt)
  all_ranks_mean <- core_microbiome(expt,threshold=2,method="mean",ranks=rank_names(expt))
  expt.all_ranks_mean <- prune_taxa(all_ranks_mean,expt)
  species_max <- core_microbiome(expt,threshold=2,method="max",ranks=c("Species"))
  expt.species_max <- prune_taxa(species_max,expt)
  all_ranks_max <- core_microbiome(expt,threshold=2,method="max",ranks=rank_names(expt))
  expt.all_ranks_max <- prune_taxa(all_ranks_max,expt)
  
  # Examine the differently defined core microbiomes
  expt_list <- c(expt.species_mean,expt.all_ranks_mean,expt.species_max,expt.all_ranks_max)
  expt_names <- c("species mean", "all ranks mean", "species max", "all ranks max")
  n <- 1
  r <- c(1,1,2,2)
  c <- c(1,2,1,2)
  grid.newpage()
  pushViewport(viewport(layout = grid.layout(2,2)))
  
  for(this_expt in  expt_list) {
      plot_title <- paste(study,"-",expt_names[n],"-",ntaxa(this_expt),"otus")
      print(plot_bar(this_expt, fill="Phylum",title=plot_title),vp=viewport(layout.pos.row = r[n], layout.pos.col = c[n]))
      expt_names[1]
      n <- n+1
  }
  
  core_compare(expt.all_ranks_mean,expt.species_mean)
  
  core_compare(expt.all_ranks_max,expt.species_max)
}

```
